<script lang="ts" setup>
import type { VueUiQuickChartConfig } from 'vue-data-ui';

import { ref } from 'vue';
import { VueUiQuickChart } from 'vue-data-ui';
import 'vue-data-ui/style.css';

const dataset = ref([
  {
    name: 'Serie1',
    values: [1, 2, 3, 2, 3, 4, 3, 4, 5],
  },
  {
    name: 'Serie2',
    values: [5, 6, 7, 6, 7, 8, 7, 8, 9],
  },
  {
    name: 'Serie3',
    values: [1, 2, 3, 5, 8, 13, 21, 13, 8],
  },
]);

const config = ref<VueUiQuickChartConfig>({
  debug: false,
  loading: false,
  responsive: false,
  barAnimated: true,
  barGap: 12,
  barStrokeWidth: 1,
  blurOnHover: true,
  chartIsBarUnderDatasetLength: 6,
  color: '#2D353C',
  dataLabelFontSize: 14,
  dataLabelRoundingPercentage: 1,
  dataLabelRoundingValue: 1,
  donutCurvedMarkers: true,
  donutHideLabelUnderPercentage: 3,
  donutLabelMarkerStrokeWidth: 1,
  donutRadiusRatio: 0.4,
  donutShowTotal: true,
  donutStrokeWidth: 2,
  donutStroke: '#FFFFFF',
  donutThicknessRatio: 0.18,
  donutTotalLabelFontSize: 24,
  donutTotalLabelOffsetY: 0,
  donutTotalLabelText: 'Total',
  donutUseShadow: false,
  donutShadowColor: '#1A1A1A',
  fontFamily: 'inherit',
  height: 338,
  legendFontSize: 12,
  legendIcon: 'circleFill',
  legendIconSize: 12,
  legendPosition: 'bottom',
  lineAnimated: true,
  lineSmooth: true,
  lineStrokeWidth: 2,
  paletteStartIndex: 0,
  showDataLabels: true,
  showLegend: true,
  showTooltip: true,
  showUserOptions: true,
  userOptionsButtons: {
    tooltip: true,
    pdf: true,
    img: true,
    fullscreen: true,
    annotator: true,
  },
  userOptionsButtonTitles: {
    open: 'Open options',
    close: 'Close options',
    tooltip: 'Toggle tooltip',
    pdf: 'Download PDF',
    img: 'Download PNG',
    fullscreen: 'Toggle fullscreen',
    annotator: 'Toggle annotator',
  },
  userOptionsPrint: {
    scale: 2,
    overflowTolerance: 0.2,
    orientation: 'auto',
  },
  title: 'A quick chart',
  titleBold: true,
  titleFontSize: 16,
  titleTextAlign: 'center',
  tooltipCustomFormat: null,
  tooltipBorderRadius: 4,
  tooltipBorderColor: '#e1e5e8',
  tooltipBorderWidth: 1,
  tooltipFontSize: 14,
  tooltipBackgroundOpacity: 30,
  tooltipPosition: 'center',
  tooltipOffsetY: 24,
  tooltipSmooth: true,
  tooltipSmoothForce: 0.18,
  tooltipSmoothSnapThreshold: 0.25,
  useCustomLegend: false,
  valuePrefix: '',
  valueSuffix: '',
  width: 512,
  xyAxisStroke: '#CCCCCC',
  xyAxisStrokeWidth: 1,
  xyGridStroke: '#d4d4d8',
  xyGridStrokeWidth: 0.5,
  xyHighlighterColor: '#000000',
  xyHighlighterOpacity: 0.05,
  xyLabelsXFontSize: 8,
  xyLabelsYFontSize: 12,
  xyPaddingBottom: 24,
  xyPaddingLeft: 24,
  xyPaddingRight: 12,
  xyPaddingTop: 24,
  xyPeriods: [
    1_767_196_800_000, 1_769_875_200_000, 1_772_294_400_000, 1_774_972_800_000,
    1_777_564_800_000, 1_780_243_200_000, 1_782_835_200_000, 1_785_513_600_000,
    1_788_192_000_000, 1_790_784_000_000, 1_793_462_400_000, 1_796_054_400_000,
    1_798_732_800_000, 1_801_411_200_000, 1_803_830_400_000, 1_806_508_800_000,
    1_809_100_800_000, 1_811_779_200_000, 1_814_371_200_000, 1_817_049_600_000,
    1_819_728_000_000,
  ],
  datetimeFormatter: {
    enable: true,
    locale: 'en',
    useUTC: false,
    januaryAsYear: false,
    options: {
      year: 'yyyy',
      month: "MMM 'yy",
      day: 'dd MMM',
      hour: 'HH:mm',
      minute: 'HH:mm:ss',
      second: 'HH:mm:ss',
    },
  },
  xyPeriodLabelsRotation: 0,
  xyPeriodLabelsAutoRotate: {
    enable: true,
    angle: -30,
  },
  xyPeriodsShowOnlyAtModulo: false,
  xyPeriodsModulo: 12,
  xyScaleSegments: 10,
  xyShowAxis: true,
  xyShowGrid: true,
  xyShowScale: true,
  yAxisLabel: 'Quantity',
  xAxisLabel: 'Time',
  axisLabelsFontSize: 12,
  userOptionsPosition: 'right',
  zoomXy: true,
  zoomColor: '#CCCCCC',
  zoomHighlightColor: '#4A4A4A',
  zoomFontSize: 14,
  zoomUseResetSlot: false,
  zoomMinimap: {
    show: true,
    smooth: true,
    selectedColor: '#1f77b4',
    selectedColorOpacity: 0.2,
    lineColor: '#1f77b4',
    selectionRadius: 2,
    indicatorColor: '#1A1A1A',
    verticalHandles: false,
    compact: true,
    merged: false,
    frameColor: '#CCCCCC',
  },
  zoomStartIndex: null,
  zoomEndIndex: null,
  showUserOptionsOnChartHover: false,
  keepUserOptionsStateOnChartLeave: true,
  zoomEnableRangeHandles: true,
  zoomEnableSelectionDrag: true,
  zoomFocusOnDrag: false,
  zoomFocusRangeRatio: 0.2,
});
</script>

<template>
  <div>
    <VueUiQuickChart :dataset="dataset" :config="config" />
  </div>
</template>
